Repository AE2-UEL/Applied-Energistics-2, pull requests merged in 2024-01, with the labels that each got.

#353 Allow for math expressions in GuiCraftAmount textbox
  src/main/java/appeng/client/gui/MathExpressionParser.java
  src/main/java/appeng/client/gui/implementations/GuiCraftAmount.java
  src/test/java/appeng/client/gui/MathExpressionParserTest.java
Labels: enhancement

#356 Tweak transparent smart cable texture
  src/main/resources/assets/appliedenergistics2/textures/parts/cable/smart/transparent.png
Labels: enhancement

#349 Part placement preview rendering + part outline render redo
  src/api/java/appeng/api/parts/IFacadeContainer.java
  src/api/java/appeng/api/parts/IPartHelper.java
  src/api/java/appeng/api/parts/IPartHost.java
  src/main/java/appeng/core/AEConfig.java
  src/main/java/appeng/core/Registration.java
  src/main/java/appeng/core/api/ApiPart.java
  src/main/java/appeng/core/sync/AppEngPacketHandlerBase.java
  src/main/java/appeng/core/sync/packets/PacketClick.java
  src/main/java/appeng/core/sync/packets/PacketPartPlacement.java
  src/main/java/appeng/facade/FacadeContainer.java
  src/main/java/appeng/hooks/RenderBlockOutlineHook.java
  src/main/java/appeng/hooks/WrenchClickHook.java
  src/main/java/appeng/items/parts/ItemFacade.java
  src/main/java/appeng/items/tools/powered/ToolColorApplicator.java
  src/main/java/appeng/parts/CableBusContainer.java
  src/main/java/appeng/parts/PartPlacement.java
  src/main/java/appeng/util/Platform.java
Labels: enhancement

#363 Fix incorrect CellInventory field types
  src/main/java/appeng/me/storage/AbstractCellInventory.java
  src/main/java/appeng/me/storage/BasicCellInventory.java
Labels: bug

#359 Initialize GHA workflows for pushing & caching
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .github/workflows/update_gradle_cache.yml
Labels: enhancement

#373 Update mod base name
  gradle.properties
Labels: enhancement

#375 Fix minor slot stack size regression
  src/main/java/appeng/container/AEBaseContainer.java
Labels: bug

#372 Fix landing/running particles for cable bus
  src/main/java/appeng/block/networking/BlockCableBus.java
  src/main/java/appeng/core/sync/AppEngPacketHandlerBase.java
  src/main/java/appeng/core/sync/network/NetworkHandler.java
  src/main/java/appeng/core/sync/packets/PacketCableBusLandingParticle.java
Labels: enhancement

#371 Add Sticky Card
  src/api/java/appeng/api/config/Settings.java
  src/api/java/appeng/api/config/Upgrades.java
  src/api/java/appeng/api/definitions/IMaterials.java
  src/api/java/appeng/api/storage/IMEInventoryHandler.java
  src/main/java/appeng/container/implementations/ContainerStorageBus.java
  src/main/java/appeng/core/Registration.java
  src/main/java/appeng/core/api/ApiClientHelper.java
  src/main/java/appeng/core/api/definitions/ApiMaterials.java
  src/main/java/appeng/core/localization/GuiText.java
  src/main/java/appeng/fluids/parts/PartFluidStorageBus.java
  src/main/java/appeng/items/materials/ItemMaterial.java
  src/main/java/appeng/items/materials/MaterialType.java
  src/main/java/appeng/me/helpers/MEMonitorHandler.java
  src/main/java/appeng/me/storage/BasicCellInventoryHandler.java
  src/main/java/appeng/me/storage/DriveWatcher.java
  src/main/java/appeng/me/storage/MEInventoryHandler.java
  src/main/java/appeng/me/storage/NetworkInventoryHandler.java
  src/main/java/appeng/parts/automation/UpgradeInventory.java
  src/main/java/appeng/parts/misc/PartStorageBus.java
  src/main/resources/assets/appliedenergistics2/lang/en_us.lang
  src/main/resources/assets/appliedenergistics2/models/item/material_card_sticky.json
  src/main/resources/assets/appliedenergistics2/recipes/materials/cardsticky.json
  src/main/resources/assets/appliedenergistics2/textures/items/material_card_sticky.png
Labels: enhancement

#374 fix classloader issue
  src/main/java/appeng/core/transformer/AE2ELTransformer.java
Labels: bug

#376 Fix minor slot regressions
  src/main/java/appeng/container/AEBaseContainer.java
Labels: bug

#385 Use LoadingCache instead of HashMap for CableBusBakedModel
  src/main/java/appeng/client/render/cablebus/CableBusBakedModel.java
  src/main/java/appeng/client/render/cablebus/CableBusModel.java
Labels: bug, enhancement

#384 Fix ME Storage Buses reporting contents regardless of settings
  src/main/java/appeng/fluids/parts/PartFluidStorageBus.java
  src/main/java/appeng/me/storage/MEInventoryHandler.java
  src/main/java/appeng/parts/misc/PartOreDicStorageBus.java
  src/main/java/appeng/parts/misc/PartStorageBus.java
Labels: bug

#392 Fix Fluid Cells having no upgrades
  src/main/java/appeng/core/Registration.java
Labels: enhancement
