Repository AE2-UEL/Applied-Energistics-2, pull requests merged in 2025-03, with the labels that each got.

#524 Fix annihilation plane not accepts drops
  src/main/java/appeng/parts/automation/PartAnnihilationPlane.java
Labels: bug

#500 Add wireless interface terminal
  src/api/java/appeng/api/definitions/IItems.java
  src/main/java/appeng/client/ClientHelper.java
  src/main/java/appeng/client/KeyBindings.java
  src/main/java/appeng/client/gui/implementations/GuiInterfaceTerminal.java
  src/main/java/appeng/client/gui/implementations/GuiWirelessInterfaceTerminal.java
  src/main/java/appeng/container/implementations/ContainerInterfaceTerminal.java
  src/main/java/appeng/container/implementations/ContainerWirelessInterfaceTerminal.java
  src/main/java/appeng/core/Registration.java
  src/main/java/appeng/core/api/definitions/ApiItems.java
  src/main/java/appeng/core/features/AEFeature.java
  src/main/java/appeng/core/sync/GuiBridge.java
  src/main/java/appeng/items/tools/powered/Terminal.java
  src/main/java/appeng/items/tools/powered/ToolWirelessInterfaceTerminal.java
  src/main/resources/assets/appliedenergistics2/lang/en_us.lang
  src/main/resources/assets/appliedenergistics2/lang/zh_cn.lang
  src/main/resources/assets/appliedenergistics2/models/item/wireless_interface_terminal.json
  src/main/resources/assets/appliedenergistics2/recipes/network/wireless_interface_terminal.json
  src/main/resources/assets/appliedenergistics2/textures/items/wireless_interface_terminal.png
Labels: enhancement

#507 Implement the remaining Lock crafting functions and fix the bugs introduced by the first part of the code
  src/api/java/appeng/api/config/LockCraftingMode.java
  src/main/java/appeng/client/gui/AEBaseGui.java
  src/main/java/appeng/client/gui/implementations/GuiInterface.java
  src/main/java/appeng/client/gui/widgets/GuiImgButton.java
  src/main/java/appeng/client/gui/widgets/GuiImgLabel.java
  src/main/java/appeng/container/implementations/ContainerInterface.java
  src/main/java/appeng/core/localization/GuiText.java
  src/main/java/appeng/helpers/DualityInterface.java
  src/main/resources/assets/appliedenergistics2/lang/en_us.lang
  src/main/resources/assets/appliedenergistics2/lang/zh_cn.lang
Labels: enhancement

#531 generalize blocking logic
  src/main/java/appeng/helpers/DualityInterface.java
Labels: bug, enhancement
